# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef51/setup-makefiles.sh

#IM-A860L
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidcfw.elf:$(TARGET_OUT_VENDOR)/etc/firmware_ef51l/vidcfw.elf \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidc.mdt:$(TARGET_OUT_VENDOR)/etc/firmware_ef51l/vidc.mdt \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidc.b00:$(TARGET_OUT_VENDOR)/etc/firmware_ef51l/vidc.b00 \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidc.b01:$(TARGET_OUT_VENDOR)/etc/firmware_ef51l/vidc.b01 

#IM-A860S
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidcfw.elf:$(TARGET_OUT_VENDOR)/etc/firmware_ef51s/vidcfw.elf \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidc.mdt:$(TARGET_OUT_VENDOR)/etc/firmware_ef51s/vidc.mdt \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidc.b00:$(TARGET_OUT_VENDOR)/etc/firmware_ef51s/vidc.b00 \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidc.b01:$(TARGET_OUT_VENDOR)/etc/firmware_ef51s/vidc.b01 

#IM-A860K
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidcfw.elf:$(TARGET_OUT_VENDOR)/etc/firmware_ef51k/vidcfw.elf \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidc.mdt:$(TARGET_OUT_VENDOR)/etc/firmware_ef51k/vidc.mdt \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidc.b00:$(TARGET_OUT_VENDOR)/etc/firmware_ef51k/vidc.b00 \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidc.b01:$(TARGET_OUT_VENDOR)/etc/firmware_ef51k/vidc.b01 

PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/bin/sensors.qcom:$(TARGET_OUT_VENDOR)/bin/sensors.qcom \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_faceproc.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_frameproc.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_frameproc.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_hdr_lib.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_image_stab.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_imx091.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_imx091.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_interface.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_interface.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_interface2.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_interface2.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_plugin.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_plugin.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_statsproc31.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_statsproc31.so \
    vendor/pantech/ef51/proprietary/lib/libmmcamera_wavelet_lib.so:$(TARGET_OUT_VENDOR)/lib/libmmcamera_wavelet_lib.so \
    vendor/pantech/ef51/proprietary/lib/liboemcamera.so:$(TARGET_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/pantech/ef51/proprietary/lib/libsensor1.so:$(TARGET_OUT_VENDOR)/lib/libsensor1.so \
    vendor/pantech/ef51/proprietary/lib/libsensor_reg.so:$(TARGET_OUT_VENDOR)/lib/libsensor_reg.so \
    vendor/pantech/ef51/proprietary/lib/libmmjpeg.so:$(TARGET_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/pantech/ef51/proprietary/lib/hw/camera.msm8960.so:$(TARGET_OUT_VENDOR)/lib/hw/camera.msm8960.so \
    vendor/pantech/ef51/proprietary/lib/hw/sensors.msm8960.so:$(TARGET_OUT_VENDOR)/lib/hw/sensors.msm8960.so \
    vendor/pantech/ef51/proprietary/lib/hw/sensors_native_hal.so:$(TARGET_OUT_VENDOR)/lib/hw/sensors_native_hal.so \
    vendor/pantech/ef51/proprietary/lib/hw/sensors_qcom.so:$(TARGET_OUT_VENDOR)/lib/hw/sensors_qcom.so

PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware/cyttsp_8064_mtp.hex:$(TARGET_OUT_VENDOR)/firmware/cyttsp_8064_mtp.hex \
    vendor/pantech/ef51/proprietary/etc/firmware/cyttsp_8960_cdp.hex:$(TARGET_OUT_VENDOR)/firmware/cyttsp_8960_cdp.hex \
    vendor/pantech/ef51/proprietary/etc/firmware/leia_pfp_470.fw:$(TARGET_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/leia_pm4_470.fw:$(TARGET_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/vidc_1080p.fw:$(TARGET_OUT_VENDOR)/firmware/vidc_1080p.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/vidc.b02:$(TARGET_OUT_VENDOR)/firmware/vidc.b02 \
    vendor/pantech/ef51/proprietary/etc/firmware/vidc.b03:$(TARGET_OUT_VENDOR)/firmware/vidc.b03 \
    vendor/pantech/ef51/proprietary/etc/firmware/libpn544_fw.so:$(TARGET_OUT_VENDOR)/firmware/libpn544_fw.so \
